### PR TITLE
Fix local imports, update for Python 3.6, fix CI

### PR DESCRIPTION
**Pull request by edurand**

### CODE REVIEW

**Comment by jni** [comment]
Thanks for this @edurand! I haven't touched this project for a long time so it looks like quite a bit needs updating. Specifically, 

- setting the Travis Python version to 3.6 should work now that python-bioformats is compatible with Python 3
- `install_requires=` should be changed to a list instead of a set because of a change in how setuptools works since this package was released.

Do you mind adding those changes? If you don't have a chance to try it, just let me know and I'll take over the PR.

Thanks again!

**Comment by edurand** [comment]
OK - just made the requested changes! But it seems the travis change to 3.6 failed

**Comment by jni** [comment]
Hmmm that's a weird failure! I suggest maybe removing the virtualenv section... But honestly I don't really know if that will help!

**Comment by jni** [comment]
Yep, Googling the error message came up with this:

https://github.com/travis-ci/travis-ci/issues/4260#issuecomment-120405756

Which suggests that we should remove that line.

**Comment by edurand** [comment]
DIfferent error now :)

**Comment by jni** [comment]
Welcome to the fun world of long term software maintenance! =P

This looks interesting and horrible but a quick fix: pin pytest-cov to `<2.6`:
https://github.com/pywbem/pywbem/issues/1371#issuecomment-418785850

**Comment by edurand** [comment]
ok, i'll stop there. let me know how you want to proceed

**Comment by jni** [comment]
@edurand FAN-tastic! Thank you for this! I checked the coverage complaining and it was nothing interesting.

**Pull request merged**
